; PlatformIO Project Configuration File
;
;   默认环境仍然保留 FreeRTOS，用于以后需要 RTOS 的场景
;   新增一个与 usb-pd-sniffer-pio 相同配置的 noneos-sdk 环境，用来验证 USB HID 枚举问题。
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:genericCH32X035F8U6]
; platform = ch32v
; board = genericCH32X035F8U6
; framework = freertos


[env:CH32X035_USB]
platform = ch32v
framework = noneos-sdk
board = genericCH32X035F8U6

build_src_filter =
	+<$PROJECT_DIR/APP/src/*>
	+<$PROJECT_DIR/APP/src/usb/*>
	+<$PROJECT_DIR/APP/src/usb_pd/*>
	+<$PROJECT_DIR/APP/src/control/*>
	+<$PROJECT_DIR/APP/src/vbus/*>
	+<$PROJECT_DIR/APP/src/log/*>
	+<$PROJECT_DIR/APP/src/memory/*>
	+<$PROJECT_DIR/APP/device/startup_ch32x035.S>

build_unflags =
	-g

build_flags =
	-Wall
	-Wextra
	-Wimplicit-function-declaration
	-Wno-unused-parameter
	-Wno-format
	-Wunused-function
	-Wunused-variable
	-Wl,--print-memory-usage
	-lprintf
	-lprintfloat
	-I APP/src

board_build.use_lto = yes
board_build.use_builtin_startup_file = no
board_build.use_builtin_system_code = yes
board_build.use_builtin_debug_code = no
board_build.cpp_support = no
board_build.ldscript = $PROJECT_DIR/APP/device/link_ch32x035.ld

monitor_speed = 921600

upload_protocol = isp


[env:CH32X035_Bootloader]
platform = ch32v
framework = noneos-sdk
board = genericCH32X035F8U6

build_src_filter =
	+<$PROJECT_DIR/Bootloader/src/*>
	+<$PROJECT_DIR/Bootloader/src/usb/*>
	+<$PROJECT_DIR/Bootloader/device/startup_ch32x035.S>

build_unflags =
	-g

build_flags =
	-Wall
	-Wextra
	-Wimplicit-function-declaration
	-Wno-unused-parameter
	-Wno-format
	-Wunused-function
	-Wunused-variable
	-Wl,--print-memory-usage
	-lprintf
	-I Bootloader/src

board_build.use_lto = yes
board_build.use_builtin_startup_file = no
board_build.use_builtin_system_code = yes
board_build.use_builtin_debug_code = no
board_build.cpp_support = no
board_build.ldscript = $PROJECT_DIR/Bootloader/device/link_bootloader.ld

upload_protocol = isp